### ISSUE TITLE
Status Update

### ISSUE THREAD

**Issue by Miserlou** [adammw/node-rtmp#1]
Any chance we can get an idea of how things are coming on this?

**Comment by adammw** [comment]
I've been hacking away at it recently, it's coming together much nicer (and more structured) than before and as a client it can connect to plain vanilla RTMP servers with the standard handshake. If you look at the test.js file, you can sort of see the structure in that you can create a client and connect similar to `net.connect`, and it will emit some events depending on the server responses. For example, the connectionListener or 'connect' should get called after a successful handshake, 'error' gets called on a `_error` invoke command, and 'close' when the connection gets closed (including because the server requested the close). The 'message' event sends through the parsed invoke messages, so yeh.
The structure is now more clear and less over the place than before, the `RTMPClient` class creates and maintains the socket, but passes off data handling off to a `RTMPMessage` instance, which in turn passes off to the `RTMPChunk` class to decode the chunk and type. The AMF decoding library has also been rewritten in a similar fashion, using more of the buffer library and a type system inspired by the ref/ffi libraries.
I'm been trying to do some of the RTMP(E)/SWF Hash handshaking as the servers I usually test with require it for anything besides an Access Denied error, but I'm not getting very far. It should also be possible to create a RTMPServer with some slight modifications, but I don't have any clients to test with so that will be much harder.
I'm currently studying for exams so going to be trying to avoid spending too much time on this in the near future, but we'll see.

**Comment by adammw** [comment]
Also see #3
